id: P94CE90D9
initial_creation_type: input
source_metadata:
  title: Drikung Tertön Ösel Dorje
  language: bo
  description: 'Texts by and about Drikung Tertön Ösel Dorje (''bri gung gter ston
    ''od gsal rdo rje):'
  volume:
    d9660119b61d45a39f6f8439dbfa11c5:
      title: 'The Concentration of Blessings: Red Tārā Lineage Prayer'
      parent: Lineage Prayers
created_at: '2022-02-28T23:04:23.606444'
last_modified_at: '2022-02-28T23:04:23.606447'
statistics:
  total_words: 674
  total_non_words: 41
quality:
  non_words_ratio: 0.06
